config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth'}
  get "devise/sessions", to: "devise/sessions#new"
  devise_scope :user do
    authenticated :user do
      root 'home#users', as: :authenticated_root
      get 'home', to: "home#users"
      resources :home do 
        collection do 
          put :table_def
          delete :table_def
        end
      end 
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :github, :google_oauth2]

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0..10]
      user.name = provider_data.info.name
      user.first_sign_in_at = Date.today
      user.last_sign_in_at = Date.today
      user.status = true
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def users
    @users = User.all
  end
  def table_def
      if params[:delete]
        user = User.where(id: params[:home_ids]).destroy_all
        redirect_to new_user_session_path
      end
      if params[:block]
        User.where(id: params[:home_ids]).update_all(status: false)
        redirect_to home_url
      end
      if params[:unblock]
        User.where(id: params[:home_ids]).update_all(status: true)
        redirect_to home_url
      end
    end
  end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController
  def facebook
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted? && @user.status != false
      sign_in_and_redirect @user
    else
      flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
      redirect_to new_user_session_path
    end 
  end

  def github
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted? && @user.status != false
      sign_in_and_redirect @user
    else
      flash[:error] = 'There was a problem signing you in through Github. Please register or try signing in later.'
      redirect_to new_user_session_path
    end
  end

  def google_oauth2
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
    if @user.persisted? && @user.status != false
      sign_in_and_redirect @user
    else
      flash[:error] = 'There was a problem signing you in through Google. Please register or try signing in later.'
      redirect_to new_user_session_path
    end 
  end

  def failure
    flash[:error] = 'There was a problem signing you in. Please register or try signing in later.' 
    redirect_to new_user_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
  def index2
    @coun = User.group("provider").count
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/users.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid ">
    <a class="navbar-brand" href="#">AuthorizationProject</a>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="nav">
        <% if user_signed_in? %>
        <li class="nav-item m-2 ">
          <a class="navbar-brand">Hello, <%= current_user.name %>, nice to meet you.</a>
        </li>
        <li class="nav-item m-2 navbar-brand">
         <%= link_to "Logout", destroy_user_session_path, :method => :delete%>
        </li>
        <% end %>
        </ul>
    </div>
  </div>
</nav>
<ul>
</ul>
<%= form_tag table_def_home_index_path, method: :delete, method: :put do %>
<%= button_tag(image_tag("Elements/delete.png", size: "35x35"), name: "delete", class: "btn btn-link") %>
<%= button_tag(image_tag("Elements/block.png", size: "35x35"), name: "block", class: "btn btn-link") %>
<%= button_tag(image_tag("Elements/unblock.png", size: "35x35"), name: "unblock", class: "btn btn-link") %>
<table class="table" id="myTable2">
  <thead class="thead-dark">
   <tr>
      <th> <input id = "main_checkbox" type="checkbox" onclick = ShowHide()> </th>
      <th onclick="sortTable(1)">Unique id</th>
      <th onclick="sortTable(2)">Name</th>
      <th>
      <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Provider
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <% for i in index2.keys do %>
      <li><a class="dropdown-item" id="myInput" onclick ="myFiltr('<%= i %>',3)"> <%= i %> <a></li>
    <% end %>
  </ul>
</div>
      </th>
      <th onclick="sortTable(4)">First sign date</th>
      <th onclick="sortTable(5)">Last sign date</th>
      <th>
      <div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    Status
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" id="myInput" onclick ="myFiltr('Block',6)"> Block </a></li>
    <li><a class="dropdown-item" id="myInput" onclick ="myFiltr('Unblock',6)"> Unblock </a></li>
  </ul>
</div>
      </th>
      <th colspan="8"></th>
    </tr>
  </thead>
    <tbody>
    <% @users.each do |user| %>
      <tr>
    
        <td><%= check_box_tag "home_ids[]", user.id %> </td>
        <td><%= user.uid %></td>
        <td><%= user.name %></td>
        <td><%= user.provider %></td>
         <td><%= user.first_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.status ? "Unblock" : "Block" %></td>
      </tr>
      <% end %>
  </tbody>
</table>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    
    <%= yield %>
   <script src="/assets/myFiltr.js?body=1"></script>
   <script src="/assets/mySort.js?body=1"></script>
   <script src="/assets/myGetCheck.js?body=1"></script>
   <script src="/assets/showhide.js?body=1"></script>
  </body>
</html>